const STORE = {
  organizacion: {
    divisiones: [
      {
        key: '1',
        division: 'CEO',
        'division-sup': 'Dirección general',
        colaboradores: 1,
        nivel: 1,
        subdivisiones: 1,
        embajadores: 'Jordyn Herwitz',
      },
      {
        key: '2',
        division: 'Mandu-Corp',
        'division-sup': 'Dirección general',
        colaboradores: 11,
        nivel: 2,
        subdivisiones: 4,
        embajadores: 'Carla Siphron',
      },
      {
        key: '3',
        division: 'Growth',
        'division-sup': 'Producto',
        colaboradores: 4,
        nivel: 2,
        subdivisiones: 3,
        embajadores: null,
      },
      {
        key: '4',
        division: 'Strategy',
        'division-sup': 'Dirección general',
        colaboradores: 6,
        nivel: 3,
        subdivisiones: 4,
        embajadores: null,
      },
      {
        key: '5',
        division: 'CEO',
        'division-sup': 'Operaciones',
        colaboradores: 11,
        nivel: 3,
        subdivisiones: 5,
        embajadores: 'Terry Press',
      },
      {
        key: '6',
        division: 'Strategy',
        'division-sup': 'Producto',
        colaboradores: 7,
        nivel: 4,
        subdivisiones: 4,
        embajadores: null,
      },
      {
        key: '7',
        division: 'Strategy',
        'division-sup': 'Dirección general',
        colaboradores: 3,
        nivel: 4,
        subdivisiones: 1,
        embajadores: 'Kierra Rosser',
      },
      {
        key: '8',
        division: 'CEO',
        'division-sup': 'Operaciones',
        colaboradores: 5,
        nivel: 4,
        subdivisiones: 4,
        embajadores: null,
      },
      {
        key: '9',
        division: 'Growth',
        'division-sup': 'Dirección general',
        colaboradores: 3,
        nivel: 2,
        subdivisiones: 1,
        embajadores: null,
      },
      {
        key: '10',
        division: 'Strategy',
        'division-sup': 'Producto',
        colaboradores: 6,
        nivel: 1,
        subdivisiones: 4,
        embajadores: null,
      },
      {
        key: '11',
        division: 'Growth',
        'division-sup': 'Dirección general',
        colaboradores: 7,
        nivel: 2,
        subdivisiones: 2,
        embajadores: null,
      },
      {
        key: '12',
        division: 'Strategy',
        'division-sup': 'Operaciones',
        colaboradores: 8,
        nivel: 5,
        subdivisiones: 4,
        embajadores: null,
      },
    ],
    colaboradores: [{}],
  },
};

export default STORE;
